### ISSUE TITLE
SUGGESTION: make client interaction based on gametick

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#150]
### Bug description

this was already discussed so we have an issue for this

**Comment by chsami** [comment]
This is already possible, take a look at the threetickbarb script


@Subscribe
    public void onGameTick(GameTick gameTick) {
        if (enabled && !inProgress) {

            switch (state) {
                case UseGuam:
                    executor.submit(this::useGuam);
                    break;
                case UseTarAndDrop:
                    executor.submit(this::useTarAndDropFish);
                    break;
                case ClickFishingSpot:
                case Idle:
                    executor.submit(this::clickFishingSpot);
                    break;
                case LocatingFishingSpot:
                    break;
                default:
                    notifier.notify("ThreeTickBarb stopped unexpectedly!");
                    break;
            }
        }
    }
