### ISSUE TITLE
Player Assistant plugin will always eat 

### ISSUE THREAD

**Issue by bzaahyo** [chsami/Microbot#176]
### Bug description

Player Assistant plugin will always eat i was using stews and it would just eat them one by one even though my health was > 51

**Comment by chsami** [comment]
Thanks for reporting thé bug. I Will fix it this evening

**Comment by bzaahyo** [comment]
if (Microbot.getClient().getLocalPlayer().getHealthRatio() > 51) return; ??

**Comment by chsami-talntr** [comment]
I just checked the script, it works fine.

You can't use health rate, it will return 1 if you're not in combat

**Comment by chsami** [comment]
> if (Microbot.getClient().getLocalPlayer().getHealthRatio() > 51) return; ??

You can't use getHealth ratio, it's not accurate.

The fix is building


https://github.com/chsami/microbot/pull/177
