### ISSUE TITLE
Barb fishing makes teak stocks

### ISSUE THREAD

**Issue by Rina-Valor** [chsami/Microbot#193]
### Bug description

The 3t barb fishing plugin makes a teak stock after awhile of running, It seemingly happens when a fish spot moves. Though not 100% sure, Its really annoying as it makes you seem extremely bot like doining perfect 3ting then making a teak stock and having to get anthor every few minutes.

Could probs be fixed by makeing it so that if the fish spot has moved more then 3 tiles away from the spot your at it will stop 3ting till it reachs the spot/makes it tap the ground while moving to cancel the 3t action.

Im not sure if it happens with guam tar

**Comment by chsami-talntr** [comment]
The 3t plugin is not an official plugin, so you'll have to contact the owner of the plugin or edit the source code yourself fixing the issue

**Comment by chsami** [comment]
Not an official plugin
