### ISSUE TITLE
Default login function chooses a random world including members even if the account is f2p

### ISSUE THREAD

**Issue by einstein95** [chsami/Microbot#227]
### Bug description

I know that at this point in the script there's no way to check if the account is a member or f2p, but want to get opinions instead of making a PR.

Function in question:
https://github.com/chsami/microbot/blob/main/runelite-client/src/main/java/net/runelite/client/plugins/microbot/util/security/Login.java#L24-L26

Should it default to only free worlds (changing `true` to `false`)?

**Comment by chsami** [comment]
When you double click a profile it will currently get a random member world to login. This is the default behaviour for double clicking a profile. 

To improve the RuneLite profile card, we should add an "isMember" checkbox. Here's a simple explanation:

Add a Checkbox: Include an "isMember" checkbox in the RuneLite profile card. Users can check this box if they have a membership.

Use the Checkbox Value: The value of this checkbox (checked or unchecked) will determine whether the user logs into member worlds or free-to-play worlds. If the box is checked, the user will be logged into member worlds. If it’s not checked, the user will be logged into free-to-play worlds.

This will make it easier for users to log into the correct type of world based on their membership status.


ALSO

You can also use autologin script which has more custom options.

![image](https://github.com/chsami/microbot/assets/23292806/64b24f83-c9db-4fc3-a5a3-ee7803e57398)
