### ISSUE TITLE
canreach does not work in instanced areas like pestcontrol

### ISSUE THREAD

**Issue by chsami** [chsami/Microbot#25]

**Comment by R-S-55** [comment]
Wrong place to put this but your Rs2NPC interact function does
Microbot.getMouse().clickFast(Random.random(0, Microbot.getClient().getCanvasWidth()), Random.random(0, Microbot.getClient().getCanvasHeight()));

which just clicks a random point on the ui

            Point point = Perspective.localToCanvas(Microbot.getClient(), npc.getLocalLocation(), 0);
            Microbot.getMouse().clickFast(point);

seems to work better. If you'd like I can put a PR for that and add a little randomization to the coords

Something is off with the VirtualMouse. It has issues with clicking npcs even when the coords are correct.

**Comment by chsami** [comment]
> Wrong place to put this but your Rs2NPC interact function does Microbot.getMouse().clickFast(Random.random(0, Microbot.getClient().getCanvasWidth()), Random.random(0, Microbot.getClient().getCanvasHeight()));
> 
> which just clicks a random point on the ui
> 
> ```
>         Point point = Perspective.localToCanvas(Microbot.getClient(), npc.getLocalLocation(), 0);
>         Microbot.getMouse().clickFast(point);
> ```
> 
> seems to work better. If you'd like I can put a PR for that and add a little randomization to the coords
> 
> Something is off with the VirtualMouse. It has issues with clicking npcs even when the coords are correct.

Is this still happening? Npc interactions seem fine on my side

**Comment by chsami** [comment]
Has been fixed with the latest version of the new web walker
