### ISSUE TITLE
MagicAction.java needs WidgetId and menuAction type set

### ISSUE THREAD

**Issue by chsami** [chsami/Microbot#28]
Inside the magicaction.java class we have a enumeration of all the spells in following format:

`WIND_STRIKE("Wind Strike", 1, 5.5f, SpriteID.SPELL_WIND_STRIKE, false, 14286855, MenuAction.WIDGET_TARGET),`

The last two numbers data points are, the widget packetID and MenuAction. We need to complete this list for spells that are not yet mapped. For example:

`ARCEUUS_LIBRARY_TELEPORT("Arceuus Library Teleport", 6, 10, SpriteID.SPELL_ARCEUUS_LIBRARY_TELEPORT, true, -1, null)`

the last two parameters are not filled in, meaning this is a spell that does not have the data filled in.

Feel free to ask questions, thanks!

**Comment by UKMonster** [comment]
done Ancients + Lunars

**Comment by chsami** [comment]
@UKMonster has this been mostly done?

**Comment by UKMonster** [comment]
> @UKMonster has this been mostly done?

i have done the ones i can so i think normal,ancients and lunars are done dont have an account for the other spells
