### ISSUE TITLE
enhancement: NMZ

### ISSUE THREAD

**Issue by bttq-dll** [chsami/Microbot#310]
### Bug description

Is it possible to add prayer flicker as option for NMZ plugin?
It's for dealing more dmg, also there's this one which is very useful to keep the 1 hp infinite-time when flicking.

![image](https://github.com/chsami/microbot/assets/167028866/4472db20-a316-4923-80f8-d8e86a60f1b5)

![RuneLite_wu3NPHrJOP](https://github.com/chsami/microbot/assets/167028866/a1363fed-a64c-40ca-a299-8496a45b3115)

**Comment by bttq-dll** [comment]
It will make our dreams last longer(more xp/points), and also the **rock dwarven cake** support would be very nice.
I believe **Guzzle** option can go down to 1 hp very fast.

Less HP you have in nmz, the less the enemies gonna hit you. 1 hp = 1 damage only, as long theres lots of absorptions, you know what i mean.

**Comment by chsami** [comment]
> It will make our dreams last longer(more xp/points), and also the **rock dwarven cake** support would be very nice. I believe **Guzzle** option can go down to 1 hp very fast.
> 
> Less HP you have in nmz, the less the enemies gonna hit you. 1 hp = 1 damage only, as long theres lots of absorptions, you know what i mean.

Rock cake should be supported. Have you tried it?

**Comment by chsami** [comment]
> ### Bug description
> Is it possible to add prayer flicker as option for NMZ plugin? It's for dealing more dmg, also there's this one which is very useful to keep the 1 hp infinite-time when flicking.
> 
> ![image](https://private-user-images.githubusercontent.com/167028866/344481753-4472db20-a316-4923-80f8-d8e86a60f1b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxNzUzLTQ0NzJkYjIwLWEzMTYtNDkyMy04MGY4LWQ4ZTg2YTYwZjFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWFhZTJiMGZmOWY3ZDRjNmUyMjcyMWY4NDY3YTQzYjQ2Mzc5NGRlYmJiNmMwMjZmNjA2ZjBlYjc1MGE5NTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bboSY-kOubmblONlCpWU122aOPWbBu3dSwU7_U4M4wg)
> 
> ![RuneLite_wu3NPHrJOP](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA) [ ![RuneLite_wu3NPHrJOP](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA) ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA) [ ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)

Would you want to pray flick quick prayers?

**Comment by bttq-dll** [comment]
> > ### Bug description
> > Is it possible to add prayer flicker as option for NMZ plugin? It's for dealing more dmg, also there's this one which is very useful to keep the 1 hp infinite-time when flicking.
> > ![image](https://private-user-images.githubusercontent.com/167028866/344481753-4472db20-a316-4923-80f8-d8e86a60f1b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxNzUzLTQ0NzJkYjIwLWEzMTYtNDkyMy04MGY4LWQ4ZTg2YTYwZjFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWFhZTJiMGZmOWY3ZDRjNmUyMjcyMWY4NDY3YTQzYjQ2Mzc5NGRlYmJiNmMwMjZmNjA2ZjBlYjc1MGE5NTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bboSY-kOubmblONlCpWU122aOPWbBu3dSwU7_U4M4wg)
> > ![RuneLite_wu3NPHrJOP](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >       
> >         [
> >           
> >             ![RuneLite_wu3NPHrJOP](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >           
> >         ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >         
> >        [ ![RuneLite_wu3NPHrJOP](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA) ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >       
> >         [
> >           
> >             ![RuneLite_wu3NPHrJOP](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >           
> >         ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/167028866/344481931-a1363fed-a64c-40ca-a299-8496a45b3115.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDIzMTEsIm5iZiI6MTcyMDA0MjAxMSwicGF0aCI6Ii8xNjcwMjg4NjYvMzQ0NDgxOTMxLWExMzYzZmVkLWE2NGMtNDBjYS1hMjk5LTg0OTZhNDViMzExNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMTI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDlhMDliNTViMDY5N2I4MTFiZGM0YjQzMGU1MDllZWQ4YzVmN2RjYmM2NjdhZDk3OTEwODZlYTUzZWU3MzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JfDHIujDApOz94IDo9ebZnm4hDM258WpS5TgSaDxxZA)
> 
> Would you want to pray flick quick prayers?

yes sir
