### ISSUE TITLE
Motherlode mine

### ISSUE THREAD

**Issue by bttq-dll** [chsami/Microbot#334]
### Bug description

The bot stucks with walking i guess on upper levels:
![image](https://github.com/user-attachments/assets/61ee302b-b9d8-441c-8cd6-6baad084c7db)

**Comment by See1Duck** [comment]
What are your webwalker settings?

**Comment by bttq-dll** [comment]
https://github.com/user-attachments/assets/1b6d693f-a390-4f6f-8684-aee73eeb9d1c

**Comment by bttq-dll** [comment]
![image](https://github.com/user-attachments/assets/b8263c15-992a-486f-9f4d-37e267bdbe34)
![image](https://github.com/user-attachments/assets/6864453e-e801-4b9a-9b68-8e753fcee4b5)
default

**Comment by bttq-dll** [comment]
> What are your webwalker settings?
might help

https://github.com/user-attachments/assets/3b7614fc-9f86-4249-a36c-a159115d3406

**Comment by See1Duck** [comment]
Set finish and recalc to the same value, I recommend putting both at 6, there are some bugs with webwalker

**Comment by bttq-dll** [comment]
still occurs. I think it only stucks when character goes to that part of map, as it just stops when there flying rock appears.
