### ISSUE TITLE
issue with walker slayer tower

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#34]
### Type

Incorrect behavior

### Operating System

MacOS

### Bug description

slayer tower doesnt seem  to work with staircases add in the transport 
        new Transport().addObstacle(new WorldPoint(3435, 3537, 0), new WorldPoint(3433, 3537, 1), "Climb-up").build();

        new Transport().addObstacle(new WorldPoint(3413, 3540, 1), new WorldPoint(3417, 3540, 2), "Climb-up").build();    

then use the walker 
Microbot.getWalker().walkTo(new WorldPoint(3431,3541,2));

### RuneLite version

latest mocroware

**Comment by ikiddoi** [comment]
also gnomestronghold cave doesnt seem to be working   

new Transport().addObstacle(new WorldPoint(2430, 9824, 0), new WorldPoint(2430, 3424, 0), "Enter").addReverse("Enter").build(); // gnome stronghold slayer cave

public static boolean walkToBankByLocation(BankLocation bankLocation, boolean useTransport) {
        Microbot.status = "Going to bank: " + bankLocation.getName();
        Microbot.getWalker().walkTo(bankLocation.getWorldPoint(), useTransport);
        if (bankLocation.getWorldPoint().distanceTo(Microbot.getClient().getLocalPlayer().getWorldLocation()) > 4) {
            Microbot.getWalker().walkTo(bankLocation.getWorldPoint(), useTransport);
            return false;
        }
        return true;
    }

  Rs2Bank.walkToBankByLocation(BankLocation.TREE_GNOME_STRONGHOLD_NIEVE, true);

**Comment by chsami** [comment]
Should be fixed in development branch, can you verifiy this @ikiddoi ?

**Comment by ikiddoi** [comment]
doesnt interact with the stairs also still stuck for me
