### ISSUE TITLE
interact broken on atlar with action use, interact broken on grounditem with cast 

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#57]
### Type

Other

### Operating System

MacOS

### Bug description

bug described in discord

### RuneLite version

latest microbot

**Comment by chsami** [comment]
Please give more context

what object exactly?
What ground item?

Code snippets?

It's really hard to go back into discord history chat logs to know what has been said

**Comment by ikiddoi** [comment]
for altar as you can see i am selecting dragon bones and using it on the the altar try inventory.interact("dragon bones"); Rs2gameobject.interact("altar","use) eventually it will break with that error seems to with sending the wrong opcode
![image](https://github.com/chsami/microbot/assets/44547988/1567c8b2-db28-420b-96a3-9a2ff02e6a6f)

**Comment by ikiddoi** [comment]
![image](https://github.com/chsami/microbot/assets/44547988/023db752-d975-424d-ba74-f1ca53976c06)
![image](https://github.com/chsami/microbot/assets/44547988/e77a4508-8b14-4889-b746-b2f6d476b560)
<img width="433" alt="image" src="https://github.com/chsami/microbot/assets/44547988/6f425007-e8b9-4cb2-9479-77a2fd4ccaf1">
![image](https://github.com/chsami/microbot/assets/44547988/c615fb6c-0fe4-4370-8988-6d904b506321)
![image](https://github.com/chsami/microbot/assets/44547988/e18c9f40-deef-48f5-9cb5-91d3895d5bd2)
![image](https://github.com/chsami/microbot/assets/44547988/76118849-429a-435d-9b8d-b547809cdb38)

**Comment by ikiddoi** [comment]
when working properly telegrabbing u get widget_target_on_ground as type but when it crashes its widget_target i tried a very long sleep before telegrabbing but that didnt seem to fix it for altar the same thing happens instead of rs2gameobject_target its doing widget_target hope this will help debugging the bug.

**Comment by chsami** [comment]
Pushed a fix for this in development
