### ISSUE TITLE
walkpath not functioning

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#58]
### Type

Incorrect behavior

### Operating System

MacOS

### Bug description

WorldPoint[] path = {
                                        new WorldPoint(3028, 3844, 0),
                                        new WorldPoint(3027, 3840, 0),
                                        new WorldPoint(3024, 3834, 0),
                                        new WorldPoint(3019, 3830, 0),
                                        new WorldPoint(3009, 3827, 0),
                                        new WorldPoint(3003, 3825, 0),
                                        new WorldPoint(2997, 3822, 0),
                                        new WorldPoint(2991, 3821, 0),
                                        new WorldPoint(2980, 3821, 0),
                                        new WorldPoint(2968, 3818, 0),
                                        new WorldPoint(2964, 3818, 0),
                                        new WorldPoint(2957, 3821, 0),
                                        new WorldPoint(2950, 3819, 0),
                                        new WorldPoint(2947, 3820, 0)
                                };
                                Microbot.getWalker().walkPath(path);
burning amulet to lvl 41 wildy --> walking to chaos altar
run that from the lvl 41 wildy spot

### RuneLite version

latest microbot

**Comment by chsami** [comment]
This should be fixed in the latest dev version

Fixed in commit https://github.com/chsami/microbot/commit/8a0afbee846bc139c1343190b726de478050ff42
