### ISSUE TITLE
findObjectById should return nearest gameobject 

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#60]
### Type

Other

### Operating System

None

### Bug description

    public static TileObject findObjectById(int id) {} currently interact with the gameobject that matches that id and click it most of the time you want to click the nearest gameobject with a certain id from you. current behaviour interacts with objects farther away from player while gameobjects of similair id's are nearby. desired behaviour interacting with the nearest gameobject. 

### RuneLite version

latest

**Comment by chsami** [comment]
It already returns the closest object for example loooking for an oak tree


![image](https://github.com/chsami/microbot/assets/23292806/622e8f81-0aab-4e7b-a857-3cc3d763912c)

**Comment by ikiddoi** [comment]
closed gave the reason for the issue in discord
