### ISSUE TITLE
nieve walking from nieve to bank and walking from back to nieve 

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#61]
### Type

Other

### Operating System

None

### Bug description

<img width="437" alt="image" src="https://github.com/chsami/microbot/assets/44547988/bb6c2772-6fc9-4460-b06e-84a371e8ea20">
first update the coords in pathfinderconfig
new Transport()
                .addObstacle(new WorldPoint(2445, 3415, 0), new WorldPoint(2445, 3415, 1), "Climb-up")
                .addReverse("Climb-down")
                .build(); //nieve stair case other side

then stand next to the staircase try to walk to bank coords at top.
current behaviour doesnt interact with the specified stairs coords
desired behaviour interacting with the specified stairs coords. 

### RuneLite version

latest

**Comment by chsami** [comment]
@ikiddoi Try to turn the settings hide roofs on

![image](https://github.com/chsami/microbot/assets/23292806/b6844ef6-5823-486f-ba28-b4f4d46c4860)

**Comment by ikiddoi** [comment]
works fine after changing back the coords
