### ISSUE TITLE
usebank not checking for npc 

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#62]
### Type

Other

### Operating System

None

### Bug description

the current implementation only checks for gameobjects while also npc can have the option banking 

current state when run at an npc with the option bank will open the bank
desired behaviour will also check for npc 
<img width="415" alt="image" src="https://github.com/chsami/microbot/assets/44547988/a083acd3-02c0-4bca-bc60-f0157a890f22">

### RuneLite version

micro

**Comment by Sunderw3k** [comment]
I'm pretty sure the old approach had this and it had poor performance because of getting the actions for each NPC/GameObject to look for `Bank`. Should consider this tho
