### ISSUE TITLE
high alch by name

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#72]
### Type

GPU

### Operating System

None

### Bug description

   public void highAlchItemByName(String name){
        Microbot.pauseAllScripts = true;
        setAlching(true);
        setItemToLoot(name);
        System.out.println("alching item");
        Tab.switchToMagicTab();

        sleep(300, 600);
        if (Tab.getCurrentTab() == InterfaceTab.MAGIC) {
            sleep(300, 600);
            Widget highAlch = Microbot.getClient().getWidget(MagicAction.HIGH_LEVEL_ALCHEMY.getWidgetId());
            Widget magicFilterButtonSelected = Rs2Widget.findWidget(1154, null);
            Widget magicFilterButton = Rs2Widget.getWidget(14287046);
            Widget show_utility_spells = Rs2Widget.findWidget(1212, null);
            // magic filterbutton is selected but we are not on the magic
            if (highAlch != null &&magicFilterButtonSelected != null && highAlch.getBounds().getX() != -1 && highAlch.getBounds().getY() != -1){
                Microbot.getMouse().click(magicFilterButtonSelected.getBounds());
                sleep(400, 600);
                highAlchItemByName(name);
                return;
            } else if (highAlch != null &&highAlch.getBounds().getX() == -1 && highAlch.getBounds().getY() == -1 && show_utility_spells != null && magicFilterButtonSelected != null ){
                Microbot.getMouse().click(show_utility_spells.getBounds());
                sleep(400, 600);
                highAlchItemByName(name);
                return;
            } else if (highAlch !=null &&highAlch.getBounds().getX() == -1 && highAlch.getBounds().getY() == -1 && show_utility_spells == null && magicFilterButtonSelected != null ){
                Microbot.getMouse().click(magicFilterButtonSelected.getBounds());
                sleep(400, 600);

                highAlchItemByName(name);
                return;
            } else if (highAlch !=null &&highAlch.getBounds().getX() == -1 && highAlch.getBounds().getY() == -1 && magicFilterButtonSelected == null && show_utility_spells == null ){
                Microbot.getMouse().click(magicFilterButton.getBounds());
                sleep(400, 600);
                highAlchItemByName(name);
                return;
            } else {
                System.out.println("test run123");
                Point point = new Point((int) highAlch.getBounds().getCenterX(), (int) highAlch.getBounds().getCenterY());
                Microbot.getMouse().click(point);
                sleep(600, 800);
                sleepUntil(() -> Microbot.getClientThread().runOnClientThread(() -> Tab.getCurrentTab() == InterfaceTab.INVENTORY), 5000);
                sleep(500, 600);
                Widget item = Inventory.findItem(name.toLowerCase());
                sleep(600);
                if (item == null) {
                    setAlching(false);
                    setLooting(false);
                    System.out.println("Item was null");
                    return;
                }
                Microbot.getMouse().click(item.getBounds());
                sleep(500,600);
                sleepUntil(() -> Microbot.getClientThread().runOnClientThread(() -> Tab.getCurrentTab() == InterfaceTab.MAGIC), 5000);
                setAlching(false);
                sleep(100);
                Microbot.pauseAllScripts = false;
            }
        } else {
            setAlching(false);
            Microbot.pauseAllScripts = false;
        }
    }

### RuneLite version

asd

**Comment by chsami** [comment]
added
