### ISSUE TITLE
disable plugins when running multiple clients  

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#89]
### Type

Other

### Operating System

None

### Bug description

plugins from other clients are active onstart should start fresh no plugins enabled when running multiple clients  

### RuneLite version

asd

**Comment by chsami** [comment]
Do you start the runelite client with the -profile arg?

**Comment by chsami** [comment]
@ikiddoi  Make sure to never close your client through IntelIJ, Make sure to close the client through the runelite UI  so your settings get saved

**Comment by ikiddoi** [comment]
with new profile system seems to work
