### ISSUE TITLE
autologin should login in random world based on settings just like runelite worldhopper. 

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#90]
### Type

Crash or hang

### Operating System

None

### Bug description

note the following function is still decent buggy but could be used to get a random world. 

`  public static Integer hopToRandomWorld(){
        if (Microbot.getClient() == null){
            return 0;
        }
        if (quickHopTargetWorld != null || Microbot.getClient().getGameState() != GameState.LOGGED_IN) return 0;
        WorldResult worlds = Microbot.getWorldService().getWorlds();
        List<Integer> listOfWorldsIntegers = new ArrayList<>();
        if (worlds == null || client.getGameState() != GameState.LOGGED_IN)
        {
            return null;
        }

        World currentWorld = worlds.findWorld(Microbot.getClient().getWorld());

        if (currentWorld == null)
        {
            return null;
        }

        EnumSet<WorldType> currentWorldTypes = currentWorld.getTypes().clone();
        currentWorldTypes.add(net.runelite.http.api.worlds.WorldType.MEMBERS);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.PVP);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.HIGH_RISK);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.BOUNTY);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.SKILL_TOTAL);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.LAST_MAN_STANDING);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.BETA_WORLD);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.DEADMAN);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.PVP_ARENA);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.QUEST_SPEEDRUNNING);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.NOSAVE_MODE);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.TOURNAMENT);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.FRESH_START_WORLD);
        currentWorldTypes.remove(net.runelite.http.api.worlds.WorldType.SEASONAL);
        for (int i = 0; i < worlds.getWorlds().size(); i++) {
            World world = worlds.getWorlds().get(i);
            if(world == null){
                continue;
            }
            if (world.getId()!= currentWorld.getId()){
                if (world.getPlayers() < 0)
                {
                    // offline world
                    continue;
                }
                if (world.getPlayers() >= 1950)
                {
                    continue;
                }
                if (world.getTypes().equals(currentWorldTypes)){
                    if (world.getAddress() != null){
                        listOfWorldsIntegers.add(world.getId());
                    }
                }
            }
        }
        Collections.shuffle(listOfWorldsIntegers);
        hopToWorld(listOfWorldsIntegers.get(0));
        return listOfWorldsIntegers.get(0);
    }
`

### RuneLite version

ads

**Comment by chsami** [comment]
feature added inlatest dev
