### ISSUE TITLE
findobject by name giving null 

### ISSUE THREAD

**Issue by ikiddoi** [chsami/Microbot#93]
### Type

Other

### Operating System

None

### Bug description

<img width="803" alt="image" src="https://github.com/chsami/microbot/assets/44547988/87127869-9470-4539-a00e-b96faf4ad83c">
blast furnance

### RuneLite version

asd

**Comment by chsami** [comment]
Should be fixed on latest dev 98c90124bd5880c7a92d1f6976ba953dd76e17ed
